version: "3.3"
services:
  car_be:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    network_mode: "host"
    volumes:
      - type: bind
        source: /home/car/driving-school-be/config/config_map.py
        target: /root/driving-school-be/config/config_map.py
