version: "3"

services:
  db:
    image: mysql/mysql-server:latest
    volumes:
      - ~/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "car"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "123"
    ports:
      - "3306:3306"
volumes:
  db_data:
